"""App settings."""

USERS_LIMIT_DEFAULT: int = 100
USERS_LIMIT_MAX: int = 300
DELAY: int = 20
REDIS_DSN: str = 'redis://localhost:6379/5'
CONNECTIONS_LIMIT = 1
CONNECTIONS_TIMEOUT = 180
CONNECTIONS_DNS_CACHE = 300
