name: Deploy

on:
  push:
    branches:
      - master

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Deploy
      run: |
        sed -i "s|%USERNAME%|${{secrets.SSH_USER}}|" etc/supervisor.conf
        sed -i "s|%USERNAME%|${{secrets.SSH_USER}}|" etc/crontab.txt

        pip install Fabric3
        fab -H ${{secrets.DESTINATION_HOST}} -u ${{secrets.SSH_USER}} -p ${{secrets.SSH_PASS}} prepare_destination_host
        fab -H ${{secrets.DESTINATION_HOST}} -u ${{secrets.SSH_USER}} -p ${{secrets.SSH_PASS}} deployment
