name: Tests

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Check dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/common.txt

    - name: wemake-python-styleguide
      uses: wemake-services/wemake-python-styleguide@0.14.1

    - name: Unittests
      run: |
        pip install -r requirements/dev.txt
        pytest --cov=app tests
