name: Tests

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Check dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/common.txt

    - name: Lint with flake8
      run: |
        pip install -r requirements/dev.txt
        flake8 app --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Unittests
      run: |
        pip install -r requirements/dev.txt
        pytest --cov=app tests
